pluginManagement {
  repositories {
    google()
    mavenCentral()
    gradlePluginPortal()
  }
}

plugins {
  id 'com.gradle.develocity' version '4.6.0'
  id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
  repositories {
    google()
    mavenCentral()
  }
}

include ':app:android'
include ':app:android-blackbox-test'
include ':app:desktop'
if (providers.gradleProperty('storymile.enableWasm').map { it.toBoolean() }.getOrElse(false)) {
  include ':app:web'
}
include ':app-framework:impl'
include ':app-framework:impl-ui-test-robots'
include ':library:impl'
include ':library:impl-robots'
include ':library:public'
include ':library:testing'
include ':logging:public'
include ':playback:impl'
include ':playback:public'
include ':presenter-navigation:impl'
include ':presenter-navigation:public'
include ':runtime-mode:impl'
include ':runtime-mode:impl-robots'
include ':runtime-mode:public'
include ':runtime-mode:testing'
include ':storage:impl'
include ':storage:public'
include ':tabs:impl'
include ':tabs:public'
include ':templates:impl'
include ':templates:public'
include ':theme:impl'
include ':theme:public'
include ':util:impl'
include ':util:public'

develocity {
    buildScan {
        def isCi = providers.environmentVariable("CI").isPresent() ||
                providers.systemProperty("CI").isPresent() ||
                providers.gradleProperty("CI").isPresent()

        if (isCi) {
            publishing.onlyIf { true }
            uploadInBackground = false
        }

        termsOfUseUrl = "https://gradle.com/terms-of-service"
        termsOfUseAgree = "yes"
    }
}

rootProject.name = 'storymile'
