plugins {
  id 'software.ralf.storymile.app.desktop'
}

storymile {
  enableComposeUi true
  enableMetro true
  enableComposePresenters true
  addImplModuleDependencies true
}

dependencies {
  commonMainImplementation project(':app-framework:impl')
  commonMainImplementation project(':theme:public')
  commonMainImplementation project(':util:public')

  desktopTestImplementation project(':app-framework:impl-ui-test-robots')
}
